const ENG = {
    menu: "Menu",
    wins: "Wins",
    losses: "Losses",
    draws: "Draws",
    bet: "Bet",
    deal: "Deal",
    allIn: "All in",
    double: "Double",
    hit: "Hit",
    stand: "Stand",
    newRound: "New round",
    resume: "Resume",
    restart: "Restart",
    stats: "Stats",
    you: "You",
    balance: "Balance",
    dealer: "Dealer",
}

const UA = {
    menu: "Меню",
    wins: "Перемоги",
    losses: "Програші",
    draws: "Нічиї",
    bet: "Ставка",
    deal: "Старт",
    allIn: "Все",
    double: "X2",
    hit: "Карта",
    stand: "Стоп",
    newRound: "Далі",
    resume: "Далі",
    restart: "Рестарт",
    stats: "Статистика",
    you: "Ви",
    balance: "Рахунок",
    dealer: "Ділер",
}
